Use string template
sepehrsoh/gango pull request #7
Opened 2023-10-31 14:36 UTC by Vedu1996

Addresses https://github.com/sepehrsoh/gango/issues/3

2023-10-31 14:41 UTC, Vedu1996 commented
Hey @sepehrsoh , I have converted all the file-content which were string within the gango source into separate template files, and then populated them as required. 
For testing out these changes, I created a sample project with the main branch(without my changes), created another with the same name on the branch with my changes, and compared them using the `diff` command in bash.
<img width="302" alt="Screenshot 2023-10-31 at 8 09 39 PM" src="https://github.com/sepehrsoh/gango/assets/28388096/d9a20d25-cfdf-44ee-a8e8-717c24de3e74">

2023-10-31 15:02 UTC, sepehrsoh commented
> Hey @sepehrsoh , I have converted all the file-content which were string within the gango source into separate template files, and then populated them as required. For testing out these changes, I created a sample project with the main branch(without my changes), created another with the same name on the branch with my changes, and compared them using the `diff` command in bash. <img alt="Screenshot 2023-10-31 at 8 09 39 PM" width="302" src="https://user-images.githubusercontent.com/28388096/279413559-d9a20d25-cfdf-44ee-a8e8-717c24de3e74.png">

for more easy test you can use make test-project command in project which is ignored by git ignore and you can see results

2023-11-01 03:58 UTC, Vedu1996 commented
Hey @sepehrsoh , I tested out using the make command and figured out there were actually some differences. I fixed them now!

2023-11-01 10:44 UTC, sepehrsoh requested changes

2023-11-01 10:44 UTC, sepehrsoh commented on templates/monitors.tmpl
> +const NameSpace = "Gango"
use ProjectName with template here too

2023-11-01 10:44 UTC, sepehrsoh commented on templates/serveFile.tmpl
> +	Short: "Serving gagngo service.",
it should be Project name here instead of gango

2023-11-01 10:44 UTC, sepehrsoh commented on utils/filio.go
>  func WriteFile(dir, path string, data string) error {
you can remove unusable function from here

2023-11-01 10:44 UTC, sepehrsoh commented on utils/filio.go
> +func EnrichTemplate(dir, path, templateFile string, data map[string]interface{}) error {
add  
```
TemplateName() string 
TemplateData(name string) map[string]interface{} 
```
methods to interface IWriteFolder placed in lib/ports.go , then instead of every time using 
```
  utils.EnrichTemplate(dir, filepath.Join(h.FilePath(), h.FileName()), h.TemplateName(), h.TemplateData()) 
  ```
   this just pass structure which implemented IWriteFolder interface

2023-11-01 10:44 UTC, sepehrsoh commented on templates/wiringFile.tmpl
> +
most of the template files start with empty line, you can use ` // Code generate by Gogango` instead

2023-11-01 12:33 UTC, Vedu1996 commented on utils/filio.go
> +func EnrichTemplate(dir, path, templateFile string, data map[string]interface{}) error {
I have extracted the functions required for writing a template into a separate interface, since for the Makefile, Dockerfile, and Readme, we do not have a IWriteFolder interface.

2023-11-01 12:34 UTC, Vedu1996 commented
@sepehrsoh Resolved the suggestions

2023-11-01 12:53 UTC, sepehrsoh commented on utils/filio.go
> +func EnrichTemplate(dir, path, templateFile string, data map[string]interface{}) error {
we can convert other files into this structure to be uniform all project

2023-11-01 12:55 UTC, sepehrsoh commented on templates/wiringFile.tmpl
> +
sorry my typo mistake it should be `// Code generate by Gango` instead of `// Code generate by Gogango`

2023-11-01 12:57 UTC, sepehrsoh commented
@Vedu1996 please squash your commit when changes has been done , thanks

2023-11-01 18:02 UTC, Vedu1996 commented
Made the changes, squashed as well.

2023-11-01 19:12 UTC, sepehrsoh approved these changes

2023-11-01 19:13 UTC, merged